# Generated by Django 2.0.3 on 2018-08-19 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('chat_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(default='profile_pic/None/no-img.jpg', upload_to='profile_pic')),
                ('locale', models.CharField(blank=True, max_length=16, null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('message_type', models.TextField(blank=True, db_index=True, max_length=64, null=True)),
                ('is_from_user', models.BooleanField()),
                ('time', models.DateTimeField(db_index=True)),
                ('intent', models.TextField(blank=True, db_index=True, max_length=256, null=True)),
                ('state', models.TextField(blank=True, db_index=True, max_length=256, null=True)),
                ('meta_raw', models.TextField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botshot.ChatLog')),
            ],
        ),
    ]
