# Generated by Django 2.1.4 on 2019-01-01 19:29

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('botshot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAction',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('at', models.TimeField(null=True)),
                ('cron', jsonfield.fields.JSONField(null=True)),
                ('until', models.DateTimeField(null=True)),
                ('action', jsonfield.fields.JSONField()),
            ],
        ),
    ]
