# Generated by Django 2.1.4 on 2019-02-15 16:07

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('botshot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAction',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('_at', models.DateTimeField()),
                ('recurrence', jsonfield.fields.JSONField(null=True)),
                ('_until', models.DateTimeField(null=True)),
                ('action', jsonfield.fields.JSONField()),
                ('conversations', jsonfield.fields.JSONField()),
            ],
        ),
    ]
