# Generated by Django 2.1.8 on 2019-06-06 09:54

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('botshot', '0002_scheduledaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='profile',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
