# Generated by Django 2.0.3 on 2019-01-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botshot', '0002_scheduledaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
