# Generated by Django 2.1.8 on 2019-06-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botshot', '0003_chatuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledaction',
            name='is_done',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='scheduledaction',
            name='_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
